"""Deploy legoscout's code to adam-server: release dirs, `current` symlink,
pm2 restart-from-current, idempotent no-op detection, rollback, status.

Mechanics are ported from CourseCraft's `scripts/deploy.sh` on this same
host -- timestamped release directories, a `current` symlink swap, and the
pm2 delete-then-start-from-`current` restart (`pm2 startOrReload` does NOT
update an existing process's cwd; CourseCraft's script found adam-server
serving a four-day-stale release because of exactly this). legoscout's
version is simpler: one pm2 app, no `.env`/secrets to symlink.

One real divergence from CourseCraft, and it is not optional: CourseCraft's
own repo is git-tracked, so a git sha is a natural "has anything changed"
signal. `_personal/` -- the whole directory legoscout's code lives in -- is
in `cli-tools`'s own `.gitignore` (`_personal/`, plus
`_repo/skills/legoscout*/` for its repo-owned skill): it was never in git
history at all, by design, so `git archive`/`git status` cannot see it.
Transport here is a plain `rsync` of the working tree instead, and the
no-op check is a dry-run rsync against whatever `current` already holds
(`--itemize-changes` prints nothing when nothing would move) rather than a
committed-content comparison. `_repo/cli-tools-shared` IS git-tracked, but
using the same rsync transport for both keeps one mechanism instead of two.
"""
from __future__ import annotations

import json
import os
import shlex
import subprocess
import time
from dataclasses import dataclass

from . import config
from .ssh import DeployError, run_local, run_remote, run_remote_script

# `.venv` is this project's own LOCAL dev/test environment (`uv run pytest`
# etc.) -- 40+MB, irrelevant to the deployed `uv tool install --editable`
# venv, and pointless to ship. `*.egg-info` is regenerated by the editable
# install itself on whichever side runs it, so shipping the local copy would
# only ever show up as a permanent, meaningless diff (different absolute
# paths baked in by each side's own install). `chromium-profile` is
# `cli_tools_shared`'s own local browser-automation runtime state -- 78MB of
# cache/cookies on this machine, gitignored there too (`**/chromium-profile/`
# in `cli-tools/.gitignore`) for exactly this reason: it is not source, and
# shipping it would hand adam-server a copy of local session data the
# display server has no use for.
_RSYNC_EXCLUDES = [
    "--exclude=__pycache__", "--exclude=*.pyc", "--exclude=.pytest_cache",
    "--exclude=.venv", "--exclude=*.egg-info", "--exclude=chromium-profile",
]


def _remote_current_exists() -> bool:
    result = run_local(
        [
            "ssh",
            config.REMOTE_HOST,
            "test -e %s && echo yes || echo no" % shlex.quote(config.REMOTE_CURRENT),
        ]
    )
    return result.strip() == "yes"


def _rsync_dry_run_changes(local_dir: str, remote_dir: str) -> str:
    """Real file-content changes a live rsync of `local_dir` -> `remote_dir`
    would make. Empty means the remote copy already matches.

    `--checksum` compares content hashes rather than size+mtime, since mtimes
    never survive an rsync+reinstall round trip the same way twice. A
    directory-only itemize line (`.d...`) means only its mtime/permission
    bookkeeping differs -- not a real content change -- so those are dropped;
    only an actual file transfer line counts.
    """
    argv = (
        ["rsync", "-a", "--delete", "-n", "--itemize-changes", "--checksum"]
        + _RSYNC_EXCLUDES
        + [f"{local_dir}/", "%s:%s/" % (config.REMOTE_HOST, remote_dir)]
    )
    out = run_local(argv)
    return "\n".join(
        line for line in out.splitlines() if line and not line.startswith(".d")
    )


def _rsync(local_dir: str, remote_dir: str) -> None:
    run_remote(["mkdir", "-p", remote_dir])
    argv = (
        ["rsync", "-a", "--delete"]
        + _RSYNC_EXCLUDES
        + [f"{local_dir}/", "%s:%s/" % (config.REMOTE_HOST, remote_dir)]
    )
    run_local(argv)


def _content_changed() -> bool:
    """True if the local working tree differs from what `current` already
    holds -- or `current` does not exist yet (first-ever deploy)."""
    if not _remote_current_exists():
        return True
    checks = [
        (config.LEGOSCOUT_SUBTREE,),
        (config.SHARED_SUBTREE,),
    ]
    for (subtree,) in checks:
        local_dir = f"{config.CLI_TOOLS_REPO}/{subtree}"
        remote_dir = f"{config.REMOTE_CURRENT}/{subtree}"
        if _rsync_dry_run_changes(local_dir, remote_dir).strip():
            return True
    return False


def _current_pm2_pid() -> int | None:
    raw = run_remote([config.PM2_BIN, "jlist"])
    try:
        procs = json.loads(raw)
    except ValueError:
        return None
    for proc in procs:
        if proc.get("name") == config.PM2_APP_NAME and proc.get("pm2_env", {}).get(
            "status"
        ) == "online":
            return proc.get("pid")
    return None


def check_port_free() -> None:
    """Refuse to deploy if `LEGOSCOUT_PORT` is already owned by something
    other than the `legoscout-display` pm2 process itself."""
    owner_pid = _current_pm2_pid()
    raw = run_remote_script(
        "lsof -iTCP:%d -sTCP:LISTEN -P -n || true\n" % config.LEGOSCOUT_PORT
    )
    for line in raw.strip().splitlines():
        if not line or line.startswith("COMMAND"):
            continue
        fields = line.split()
        pid = int(fields[1])
        if pid != owner_pid:
            raise DeployError(
                "port %d on %s is already in use by PID %d (%s), not the "
                "legoscout-display pm2 process -- refusing to deploy. Free "
                "the port or move legoscout to a different one.\n%s"
                % (config.LEGOSCOUT_PORT, config.LEGOSCOUT_HOST, pid, fields[0], line)
            )


def _restart_pm2_from_current() -> None:
    # ecosystem.config.cjs lives inside the legoscout subtree itself
    # (`_personal/legoscout/ecosystem.config.cjs`), not at the release dir's
    # root -- unlike CourseCraft's flat layout, `current` is one level above
    # where pm2's own `cwd: __dirname` actually resolves. Every reference
    # below points at that nested directory, not bare `current`.
    ecosystem_dir = f"{config.REMOTE_CURRENT}/{config.LEGOSCOUT_SUBTREE}"
    script = """set -euo pipefail
expected="$(readlink -f '{ecosystem_dir}')"
names="$(node -e "console.log(require('{ecosystem_dir}/ecosystem.config.cjs').apps.map(a => a.name).join(' '))")"
for app in $names; do
  if [ "$({pm2} id "$app")" != "[]" ]; then
    {pm2} delete "$app"
  fi
done
{pm2} start '{ecosystem_dir}/ecosystem.config.cjs'
{pm2} save
for app in $names; do
  cwd="$({pm2} jlist | node -e "
let s='';
process.stdin.on('data', d => s += d).on('end', () => {{
  const p = JSON.parse(s).find(x => x.name === process.argv[1]);
  console.log(p ? p.pm2_env.pm_cwd : '');
}});" "$app")"
  if [ "$cwd" != "$expected" ]; then
    echo "pm2 cwd for $app is '$cwd', expected '$expected'" >&2
    exit 1
  fi
  echo "pm2 $app running from $cwd"
done
""".format(ecosystem_dir=ecosystem_dir, pm2=config.PM2_BIN)
    run_remote_script(script)


def _prune_releases() -> None:
    script = """set -euo pipefail
cd '{releases}'
current_name="$(basename "$(readlink '{current}')")"
{{ echo "$current_name"; ls -1 | sort -r | head -n {keep}; }} | sort -u > /tmp/legoscout-keep-releases.txt
to_prune="$(ls -1 | grep -v -F -x -f /tmp/legoscout-keep-releases.txt || true)"
if [ -n "$to_prune" ]; then
  while read -r old; do
    rm -rf "$old"
  done <<< "$to_prune"
fi
rm -f /tmp/legoscout-keep-releases.txt
""".format(releases=config.REMOTE_RELEASES, current=config.REMOTE_CURRENT, keep=config.KEEP_RELEASES)
    run_remote_script(script)


def _http_reachable() -> bool:
    argv = ["curl", "-fs", "-o", "/dev/null", "--max-time", "1", config.LEGOSCOUT_URL]
    return subprocess.run(argv, capture_output=True).returncode == 0


def verify_reachable() -> None:
    deadline = time.monotonic() + config.REACHABLE_TIMEOUT_SECONDS
    while time.monotonic() <= deadline:
        if _http_reachable():
            return
        time.sleep(1)
    raise DeployError(
        "%s did not become reachable within %ds"
        % (config.LEGOSCOUT_URL, config.REACHABLE_TIMEOUT_SECONDS)
    )


@dataclass
class DeployResult:
    skipped: bool
    release_name: str | None


def deploy_code() -> DeployResult:
    """No-op if adam-server's `current` already matches the local working
    tree; otherwise rsync, install, symlink, restart, prune, verify."""
    if not _content_changed():
        return DeployResult(skipped=True, release_name=None)

    check_port_free()

    timestamp = time.strftime("%Y%m%d%H%M%S", time.gmtime())
    release_name = f"{timestamp}-{os.urandom(3).hex()}"
    release_dir = f"{config.REMOTE_RELEASES}/{release_name}"

    _rsync(
        f"{config.CLI_TOOLS_REPO}/{config.LEGOSCOUT_SUBTREE}",
        f"{release_dir}/{config.LEGOSCOUT_SUBTREE}",
    )
    _rsync(
        f"{config.CLI_TOOLS_REPO}/{config.SHARED_SUBTREE}",
        f"{release_dir}/{config.SHARED_SUBTREE}",
    )

    run_remote_script(
        "set -euo pipefail\n%s tool install --editable %s --force\n"
        % (config.UV_BIN, shlex.quote(f"{release_dir}/{config.LEGOSCOUT_SUBTREE}"))
    )

    run_remote(["ln", "-sfn", release_dir, config.REMOTE_CURRENT])
    _restart_pm2_from_current()
    _prune_releases()
    verify_reachable()

    return DeployResult(skipped=False, release_name=release_name)


def status() -> dict:
    remote_release = None
    if _remote_current_exists():
        remote_release = run_remote(
            ["sh", "-c", "basename \"$(readlink %s)\"" % shlex.quote(config.REMOTE_CURRENT)]
        ).strip()
    releases_raw = run_remote(["sh", "-c", "ls -1t %s 2>/dev/null" % shlex.quote(config.REMOTE_RELEASES)])
    releases = [r for r in releases_raw.splitlines() if r]
    pm2_raw = run_remote([config.PM2_BIN, "jlist"])
    try:
        pm2_procs = json.loads(pm2_raw)
    except ValueError:
        pm2_procs = []
    pm2_status = [
        {
            "name": p["name"],
            "status": p["pm2_env"]["status"],
            "restarts": p["pm2_env"]["restart_time"],
            "pm_cwd": p["pm2_env"].get("pm_cwd"),
        }
        for p in pm2_procs
        if p.get("name") == config.PM2_APP_NAME
    ]
    return {
        "content_in_sync": not _content_changed(),
        "remote_release": remote_release,
        "releases": releases,
        "pm2": pm2_status,
    }


def rollback(target: str = "1") -> str:
    sorted_releases = [
        r
        for r in run_remote(["sh", "-c", "cd %s && ls -1 | sort -r" % shlex.quote(config.REMOTE_RELEASES)]).splitlines()
        if r
    ]
    if not _remote_current_exists():
        raise DeployError("no current release on adam-server to roll back from")
    current_name = run_remote(
        ["sh", "-c", "basename \"$(readlink %s)\"" % shlex.quote(config.REMOTE_CURRENT)]
    ).strip()

    if target.isdigit():
        try:
            idx = sorted_releases.index(current_name)
            target_name = sorted_releases[idx + int(target)]
        except (ValueError, IndexError):
            raise DeployError("not enough releases to roll back %s step(s)" % target)
    else:
        target_name = target

    if target_name not in sorted_releases:
        raise DeployError("release not found: %s" % target_name)
    if target_name == current_name:
        return target_name

    check_port_free()
    run_remote(["ln", "-sfn", f"{config.REMOTE_RELEASES}/{target_name}", config.REMOTE_CURRENT])
    _restart_pm2_from_current()
    verify_reachable()
    return target_name
