"""Documented Impact Publisher endpoint catalog.

Source: https://integrations.impact.com/impact-publisher/reference/overview
"""

ENDPOINTS = [
    {"command": "account get", "method": "GET", "path": "/CompanyInformation"},
    {"command": "account update", "method": "PUT", "path": "/CompanyInformation"},
    {"command": "account users list", "method": "GET", "path": "/Users"},
    {"command": "account users get", "method": "GET", "path": "/Users/{user_id}"},
    {"command": "account invoices list", "method": "GET", "path": "/Invoices"},
    {"command": "account invoices get", "method": "GET", "path": "/Invoices/{invoice_id}"},
    {"command": "account invoices download", "method": "GET", "path": "/Invoices/{invoice_id}/Download"},
    {"command": "account tax-documents list", "method": "GET", "path": "/TaxDocuments"},
    {"command": "account tax-documents get", "method": "GET", "path": "/TaxDocument/{tax_document_id}"},
    {"command": "account tax-documents latest", "method": "GET", "path": "/TaxDocument"},
    {"command": "account tax-documents create", "method": "POST", "path": "/TaxDocument"},
    {"command": "account tax-documents complete", "method": "POST", "path": "/TaxDocument/Complete"},
    {"command": "account withdrawal-settings get", "method": "GET", "path": "/WithdrawalSettings"},
    {"command": "account withdrawal-settings update", "method": "PUT", "path": "/WithdrawalSettings"},
    {"command": "account withdrawal-settings required-fields", "method": "GET", "path": "/WithdrawalSettings/RequiredFields"},
    {"command": "campaigns list", "method": "GET", "path": "/Campaigns"},
    {"command": "campaigns get", "method": "GET", "path": "/Campaigns/{campaign_id}"},
    {"command": "campaigns logo", "method": "GET", "path": "/Campaigns/{campaign_id}/Logo"},
    {"command": "campaigns contracts list", "method": "GET", "path": "/Contracts"},
    {"command": "campaigns contracts get", "method": "GET", "path": "/Contracts/{contract_id}"},
    {"command": "campaigns contracts active", "method": "GET", "path": "/Campaigns/{campaign_id}/Contracts/Active"},
    {"command": "campaigns contracts public-terms", "method": "GET", "path": "/Campaigns/{campaign_id}/PublicTerms/Download"},
    {"command": "campaigns promotions list", "method": "GET", "path": "/Promotions"},
    {"command": "campaigns promotions get", "method": "GET", "path": "/Promotions/{promotion_id}"},
    {"command": "campaigns deals list", "method": "GET", "path": "/Campaigns/{campaign_id}/Deals"},
    {"command": "campaigns deals get", "method": "GET", "path": "/Campaigns/{campaign_id}/Deals/{deal_id}"},
    {"command": "campaigns tracking-link", "method": "POST", "path": "/Programs/{program_id}/TrackingLinks"},
    {"command": "ads list", "method": "GET", "path": "/Ads"},
    {"command": "ads get", "method": "GET", "path": "/Ads/{ad_id}"},
    {"command": "ads code", "method": "GET", "path": "/Ads/{ad_id}/Code"},
    {"command": "ads iframe-code", "method": "GET", "path": "/Ads/{ad_id}/IFrameCode"},
    {"command": "ads tracking-link", "method": "GET", "path": "/Ads/{ad_id}/TrackingLink"},
    {"command": "actions list", "method": "GET", "path": "/Actions"},
    {"command": "actions get", "method": "GET", "path": "/Actions/{action_id}"},
    {"command": "actions items", "method": "GET", "path": "/Actions/{action_id}/Items"},
    {"command": "actions item", "method": "GET", "path": "/Actions/{action_id}/Items/{sku}"},
    {"command": "actions updates list", "method": "GET", "path": "/ActionUpdates"},
    {"command": "actions updates get", "method": "GET", "path": "/ActionUpdates/{update_id}"},
    {"command": "actions inquiries list", "method": "GET", "path": "/ActionInquiries"},
    {"command": "actions inquiries get", "method": "GET", "path": "/ActionInquiries/{inquiry_id}"},
    {"command": "actions inquiries create", "method": "POST", "path": "/ActionInquiries"},
    {"command": "catalogs list", "method": "GET", "path": "/Catalogs"},
    {"command": "catalogs get", "method": "GET", "path": "/Catalogs/{catalog_id}"},
    {"command": "catalogs items", "method": "GET", "path": "/Catalogs/{catalog_id}/Items"},
    {"command": "catalogs item", "method": "GET", "path": "/Catalogs/{catalog_id}/Items/{item_id}"},
    {"command": "catalogs search", "method": "GET", "path": "/Catalogs/ItemSearch"},
    {"command": "catalogs stores list", "method": "GET", "path": "/Stores"},
    {"command": "catalogs stores get", "method": "GET", "path": "/Stores/{store_id}"},
    {"command": "catalogs stores items", "method": "GET", "path": "/Stores/{store_id}/Group/{group_id}/Items"},
    {"command": "catalogs exception-lists show", "method": "GET", "path": "/ExceptionLists/{exception_list_id}"},
    {"command": "catalogs exception-lists items", "method": "GET", "path": "/ExceptionLists/{exception_list_id}/Items"},
    {"command": "catalogs promo-code-exception-lists show", "method": "GET", "path": "/PromoCodeExceptionLists/{exception_list_id}"},
    {"command": "catalogs promo-code-exception-lists items", "method": "GET", "path": "/PromoCodeExceptionLists/{exception_list_id}/Items"},
    {"command": "reports list", "method": "GET", "path": "/Reports"},
    {"command": "reports run", "method": "GET", "path": "/Reports/{report_id}"},
    {"command": "reports get", "method": "GET", "path": "/Reports/{report_id}/MetaData"},
    {"command": "reports metadata", "method": "GET", "path": "/Reports/{report_id}/MetaData"},
    {"command": "reports export", "method": "GET", "path": "/ReportExport/{report_id}"},
    {"command": "clicks retrieve", "method": "GET", "path": "/Clicks/{click_id}"},
    {"command": "clicks export", "method": "GET", "path": "/ClickExport"},
    {"command": "jobs history", "method": "GET", "path": "/Jobs"},
    {"command": "jobs status", "method": "GET", "path": "/Jobs/{job_id}"},
    {"command": "jobs download", "method": "GET", "path": "/Jobs/{job_id}/Download"},
    {"command": "jobs replay", "method": "PUT", "path": "/Jobs/{job_id}/Replay"},
    {"command": "websites list", "method": "GET", "path": "/MediaProperties"},
    {"command": "websites get", "method": "GET", "path": "/MediaProperties/{website_id}"},
    {"command": "websites create", "method": "POST", "path": "/MediaProperties"},
    {"command": "websites update", "method": "PUT", "path": "/MediaProperties/{website_id}"},
    {"command": "websites delete", "method": "DELETE", "path": "/MediaProperties/{website_id}"},
]
